### ISSUE TITLE
Error on click invaliatecache Joomla 4.0 RC2

### ISSUE THREAD

**Issue by Stuartemk** [dgrammatiko/invalidate-cache#13]
Uncaught (in promise) ReferenceError: error is not defined
    at HTMLAnchorElement.<anonymous> (default.js?59f7b3bd0de3c11c9bf15ff2a6503399:21)

    if (typeof resp !== 'object' || !resp.ok || resp.statusText !== 'OK') {
      renderMessage(error, ['Something blew up!']);

**Comment by dgrammatiko** [comment]
Fixed: https://github.com/dgrammatiko/invalidate-cache/commit/511d5a7b9990af37f5b1fea2425cb875859de5cb

Will create a new release as well

**Comment by dgrammatiko** [comment]
As the issue was fixed I'm closing this. Thanks for reporting
