### ISSUE TITLE
"blew up" error msg

### ISSUE THREAD

**Issue by woluweb** [dgrammatiko/invalidate-cache#33]
Hi @dgrammatiko 

If you remember, there was this "blew up" error msg that you solved on the "dev.festival___" website.

Good news: it still works.
Bad news: I installed the Module on another site... and there it also always says that it "blew up".

Could it be that the fix is not integrated in the repo?

Txs

**Comment by dgrammatiko** [comment]
What are the versions for Joomla and this module?

**Comment by woluweb** [comment]
using 4.1.2 version for Joomla (of course ;) )
And using the download button on https://invalidate-cache.dgrammatiko.dev/ for the Module

**Comment by dgrammatiko** [comment]
Do you get any errors in your browser's console?

**Comment by woluweb** [comment]
ohhh, yes indeed:

```
Failed to load resource: the server responded with a status of 500 ()   
https://2022.MYDOMAIN.eu//administrator/index.php?option=com_ajax&format=json&module=invalidatecache&method=invalidate&e7e37371e0640a3e625e52158a3a502a=1
```

and that link starts with
```
{
error: true,
code: 0,
message: "Not Allowed",
trace:
```

**Comment by dgrammatiko** [comment]
Ok, let me know if version 0.0.11 is ok

**Comment by woluweb** [comment]
(well, I can't find any download link to 0.0.11 here or on https://invalidate-cache.dgrammatiko.dev/ where it is still 0.0.10)

**Comment by dgrammatiko** [comment]
It should be there now, I forgot to publish the changes.

**Comment by woluweb** [comment]
Even before clicking there is an error in the Console now:
```
Uncaught ReferenceError: el is not defined
default.js?13a681acaa7ef0332e5d429bc971888b:33 
    at default.js?13a681acaa7ef0332e5d429bc971888b:33:3
    at Array.forEach (<anonymous>)
    at default.js?13a681acaa7ef0332e5d429bc971888b:10:2
```

**Comment by dgrammatiko** [comment]
Ooops, could you uninstall it and re download it and install it? I messed up a file

**Comment by woluweb** [comment]
not yet it seems :D

```
default.js?f532fbb0569de5b8dca2eedf713edb68:19          POST https://2022.brusselssmile.eu/administrator/index.php?option=com_ajax&format=json&module=invalidatecache&method=invalidate&e7e37371e0640a3e625e52158a3a502a=1 500
(anonymous) @ default.js?f532fbb0569de5b8dca2eedf713edb68:19
default.js?f532fbb0569de5b8dca2eedf713edb68:26

Uncaught (in promise) ReferenceError: err is not defined
    at HTMLAnchorElement.<anonymous> (default.js?f532fbb0569de5b8dca2eedf713edb68:26:21)
(anonymous) @ default.js?f532fbb0569de5b8dca2eedf713edb68:26
```

**Comment by dgrammatiko** [comment]
Can you try the same as before?

**Comment by woluweb** [comment]
what do you mean?
uninstall and reinstall 0.0.11?

**Comment by dgrammatiko** [comment]
yes, and then post what's the error you're getting

**Comment by dgrammatiko** [comment]
Do you have Debug enabled?

**Comment by woluweb** [comment]
yes, since this evening.
But the error msg is also there when I disable Debug mode (just tested)
I send you credentials by email

**Comment by dgrammatiko** [comment]
Ok @woluweb , so 0.0.11 should be fine now. You can destroy the temp user

Thanks for reporting and letting me use the machine to figure out the bug

**Comment by woluweb** [comment]
I tested the latest version on https://subform.joomlacustomfields.org/ (where it had always been on "blew up") and now it works there too.
Txs for the new version. Exciting :)
